name: hw1_chuck_norris_tinder
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  http: 0.13.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  cupertino_icons: ^1.0.2
  injectable: ^1.5.0
  url_launcher: ^6.1.10
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/croco.jpg
    - assets/images/photo.jpg
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf