name: hw1_chuck_norris_tinder
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  http: 0.13.4
  flutter:
    sdk: flutter
  firebase_core: ^1.3.0
  firebase_database: ^7.1.1
  firebase_core_platform_interface: 4.5.1
  firebase_messaging: ^13.0.4
  flutter_riverpod: ^2.0.2
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.10
  json_annotation: ^4.0.1
  connectivity_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  flutter_launcher_icons: "^0.12.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/croco.jpg
    - assets/images/photo.jpg
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf